### PR TITLE
Move generateRunClass from DeployPlugin to CoreSettingsPlugin.

### PR DESCRIPTION
**Pull request by jkinkead**
Simple!

### CODE REVIEW

**Comment by cristipp** [comment]
Many thanks for this! It would have taken me much longer to figure out all the places to do the change :)

**Comment by cristipp** [comment]
How do we make use of this new feature in s2 project?

**Comment by jkinkead** [comment]
I'll `sbt release` the plugins project, then you update to the latest version.

**Comment by jkinkead** [comment]
Version `2015.05.20-0` released.

**Comment by cristipp** [comment]
Thanks!

**Pull request merged**
