### PR TITLE
Convert style warnings to errors

### PR DESCRIPTION
**Pull request by cristipp**
How do I build & publish a new version of the plugins?

### CODE REVIEW

**Comment by cristipp** [comment]
FYI @rlebras

**Comment by schmmd** [comment]
@cristipp what problem are you trying to fix exactly?  I worry that this PR followed by a new release of sbt-plugins will not address your problem.

Currently you are using [allenai-sbt-plugins 1.1.1](https://github.com/allenai/euclid/blob/master/project/plugins.sbt).  A new release would mean you would need to upgrade to [1.5.3](https://github.com/allenai/sbt-plugins/blob/master/version.sbt).  1.1.1 was [released in October 2015](https://github.com/allenai/sbt-plugins/releases/tag/v1.1.1) so I would guess that upgrading would be a nightmare.

What is the exact problem you are running into?

**Comment by cristipp** [comment]
Problem: We have just cleaned up hundreds of scalastyle warnings from our build. We'd like to seal the deal and prevent new scalastyle warnings to be added to the codebase.

**Comment by cristipp** [comment]
Oh, by the way, I intended to make this PR against an _euclid_ branch, but apparently I failed to do so. Give me a few more minutes.

**Comment by cristipp** [comment]
Moving over to #290, which merges changes into euclid branch.

**Pull request closed without merging**
