### PR TITLE
Update common

### PR DESCRIPTION
**Pull request by row11**
Adding allenAiIndexing as a library to CoreDependencies

### CODE REVIEW

**Comment by row11** [comment]
@jkinkead maybe you want to double check this is kosher :)

**Comment by sbhaktha** [comment]
LGTM! Merge on Jesse! :)

**Comment by jkinkead** [comment]
v1.0.18 of common isn't quite released yet, but it should be shortly! Once it's on [bintray](https://bintray.com/allenai/maven), this LGTM.

**Comment by row11** [comment]
Looks like it was just released! Merging.

**Pull request merged**
